version: '3.2'

services:
  abuild:
    build:
      context: ..
      dockerfile: .docker/abuild/Dockerfile
    container_name: phpearth-abuild
    volumes:
      - ../repo:/repo
      - ../build:/build
      - ../repo/phpearth.rsa.pub:/home/packager/.abuild/phpearth.rsa.pub
      - ../build/phpearth.rsa.priv:/home/packager/.abuild/phpearth.rsa.priv
    working_dir: /build
