version: '3.3'

services:
  abuild:
    build:
      context: ..
      dockerfile: .docker/abuild/Dockerfile
    container_name: phpearth-abuild
    volumes:
      - ../repo:/repo
      - ../build:/build
    working_dir: /build
