version: '3.1'

services:
  app:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./.docker/app/Dockerfile
    restart: always
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
    networks:
      - dockerphp

networks:
  dockerphp:
    driver: bridge
