version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8088
      - 7080:7080
    volumes:
      - ./var/lib/openlitespeed/app:/var/lib/openlitespeed/app
